#------------------------------------------------------------------
# Main config file for NoHack
#------------------------------------------------------------------

#################################################################################
#
#                NoHack Basic Config Section
#
#################################################################################

#If set to true, random npc players will spawn around the player detecting if some kind of killaura is enabled
check-killaura: true

#If set to true, spawned npc players will be invisible.
#Some hacked clients attack invisible players, while others do not
npc-invisible: false

#If true, npcs will only spawn in spots undetectable to legit players
check-killaura-no-annoy: true

#List the commands to issue, without the /, when the plugin detects a possible killaura mod
check-killaura-commands:
- say .name. is hacking!

#################################################################################
#
#                NoHack Messages Section
#
#################################################################################
format: '&c[NoHack] &e.name.&a failed &2.type.&a! .message. &8VL .vl.'

#Chat violation messages
chat-impossible-message: 'Tried to chat in an illegal state.'

#Move violation messages
nofall-message: 'Tried to fall while saying on the ground.'

timer-message: 'Sent .packets-sent. packets but expected no more than .expected-packets..'

impossible-move-message: 'Tried to move in a way which is impossible.'

vertical-speed-message: 'Tried to move too fast on the y axis.'

horizontal-speed-message: 'Tried to move too fast on the xz axis.'

fly-message: 'Tried to fly in survival mode without permission.'

glide-message: 'Tried to float to an unexpected location.'

#Block violation messages
block-visible-break-message: 'Tried to break another block than expected.'

speed-break-message: 'Broke blocks faster than usal.'

#Fight violation messages
godmode-message: 'Tried to avoid taking damage.'

fight-knockback-message: 'Tried to knockback an entity in an impossible state.'

fight-impossible-message: 'Tried to do illegal attacks.'

fight-visible-message: 'Tried to do attack a target without looking at it.'

fight-speed-message: 'Tried to attack too fast.'

fight-reach-message: 'Tried to attack too far.'

autosoup-message: 'Tried to soup while attacking!'

#Inventory violation messages
inventory-impossible-message: 'Tried to do illegal inventory clicks.'

inventory-click-speed: 'Clicked a container too fast.'

#Everything else with messages
noswing-message: 'Did not swing arm.'

fast-eat-message: 'Ate a food item too fast.'
#################################################################################
#
#                NoHack Advance Section
#
#################################################################################

###############################################################
#    Notice: Below, this changes how the plugin works
#    Only modify if you know what you are doing!
###############################################################

noswing-block-difference: 2500

noswing-fight-difference: 100

fight-attack-speed: 60

inventory-click-max-speed: 50

max-packets: 14