name: NoHack
version: 1.0
main: me.johnnywoof.NoHack
softdepend: [ProtocolLib, NoCheatPlus, AntiCheat]
commands:
    nohack:
        description: NoHack command
        usage: /nohack
        aliases: [nh]